//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace TagConfig.Models
{
 /// <summary>
    /// 实体类Condition。
    /// </summary>
   
    [Serializable]
    public  class Condition 
    {
        #region Model
            public int TypeID{set;get;}
            public string Source{set;get;}
            public int AlarmType{set;get;}
            public int EventType{set;get;}
            public int ConditionType{set;get;}
            public decimal Para{set;get;}
            public bool IsEnabled{set;get;}
            public decimal DeadBand{set;get;}
            public int Delay{set;get;}
            public string Comment{set;get;}
        #endregion
	}
}