//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace TagConfig.Models
{
 /// <summary>
    /// 实体类Membership。
    /// </summary>
   
    [Serializable]
    public  class Membership 
    {
        #region Model
            public int ID{set;get;}
            public string UserName{set;get;}
            public string Password{set;get;}
            public short Role{set;get;}
            public string Email{set;get;}
            public string Phone{set;get;}
        #endregion
	}
}