//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace TagConfig.Models
{
 /// <summary>
    /// 实体类Scale。
    /// </summary>
   
    [Serializable]
    public  class Scale 
    {
        #region Model
            public short ScaleID{set;get;}
            public int ScaleType{set;get;}
            public decimal? EUHi{set;get;}
            public decimal? EULo{set;get;}
            public decimal? RawHi{set;get;}
            public decimal? RawLo{set;get;}
        #endregion
	}
}