//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace TagConfig.Models
{
 /// <summary>
    /// 实体类SubCondition。
    /// </summary>
   
    [Serializable]
    public  class SubCondition 
    {
        #region Model
            public int ConditionID{set;get;}
            public int SubAlarmType{set;get;}
            public decimal Threshold{set;get;}
            public int Severity{set;get;}
            public string Message{set;get;}
            public bool IsEnable{set;get;}
        #endregion
	}
}