//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace TagConfig.Models
{
 /// <summary>
    /// 实体类Tag。
    /// </summary>
   
    [Serializable]
    public  class Tag 
    {
        #region Model
            public short TagID{set;get;}
            public string TagName{set;get;}
            public int DataType{set;get;}
            public short DataSize{set;get;}
            public string Address{set;get;}
            public short GroupID{set;get;}
            public bool IsActive{set;get;}
            public bool Archive{set;get;}
            public object DefaultValue{set;get;}
            public string Description{set;get;}
            public decimal Maximum{set;get;}
            public decimal Minimum{set;get;}
            public int Cycle{set;get;}
            public DateTime RowVersion{set;get;}
        #endregion
	}
}